// Code generated by tygo. DO NOT EDIT.

//////////
// source: master_handlers.go

export const InitiateTrainingResponseID = "initiate-training";
export const StartTrainingResponseID = "start-training";
export const PauseTrainingResponseID = "pause-training";
export const PingResponseID = "ping";
export const GetAllClientsResponseID = "get-all-clients";
export interface InitiateTrainingResponse {
  id: string;
  initial_params: any;
  search_space: any;
}
export interface StartTrainingResponse {
  id: string;
}
export interface PauseTrainingResponse {
  id: string;
}
export interface PingResponse {
  id: string;
}
export interface GetAllClientsResponse {
  id: string;
}

//////////
// source: master_messages.go

export const PongMessageId = "pong";
export const ClientConnectedMessageID = "client-connected";
export const ClientDisconnectedMessageID = "client-disconnected";
export const AllClientsMessageID = "get-all-clients";
export const ClientFinishedTrainingMessageID = "client-finished-training";
export const ClientStartedTrainingMessageID = "client-started-training";
export const TrainingCompletedMessageID = "training-completed";
export const ClientReadyToTrainMessageID = "ready-to-train";
export const ClientNotReadyToTrainMessageID = "not-ready-to-train";
export interface PongMessage {
  id: string;
}
export interface WorkerInfo {
  worker_id: string;
  ip: string;
  status: number /* int */;
  name: string;
}
export interface ClientConnectionStatusMessage {
  id: string;
  worker: WorkerInfo;
}
export interface ClientStartedTrainingMessage {
  id: string;
  worker_id: string;
  parameters_id: string;
  parameters: any;
  time_started: number /* int64 */;
}
export interface ClientFinishedTrainingMessage {
  id: string;
  worker_id: string;
  parameters_id: string;
  loss: number /* float64 */;
  time_finished: number /* int64 */;
}
export interface ClientReadyToTrainMessage {
  id: string;
  worker_id: string;
}
export interface GetAllClientsMessage {
  id: string;
  workers: WorkerInfo[];
}
export interface UploadFilesMessage {
  model_file_id: string;
  training_file_id: string;
  evaluation_file_id: string;
}

//////////
// source: message.go

export interface Message {
  id: string;
}
